# Generated by Django 4.2.3 on 2023-07-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Laptops", "Laptops"),
                    ("Arts", "Arts"),
                    ("Food", "Food"),
                    ("Home", "Home"),
                    ("Kitchen", "Kitchen"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
